### ISSUE TITLE
iOS 14.4.1 Crash, Persists with all tweaks disabled besides itself + Dependancies

### ISSUE THREAD

**Issue by iosrouter** [ginsudev/ProtectedBrowser#2]
Date: 8/20/22, 7:40 PM
Process: SpringBoard
Bundle id: com.apple.springboard
Device: iPhone 12 Pro Max, iOS 14.4.1
Bundle version: 1.0
Exception type: EXC_BREAKPOINT (SIGTRAP)
Exception subtype: (null)
Exception codes: 0x0000000000000000, 0x00000001afb83a18
Culprit: ProtectedBrowser.dylib
Triggered by thread: 0
Thread name: Dispatch queue: com.apple.main-thread
Call stack:
0   libswiftCore.dylib                0x00000001afb83a18 0x1afb4d000 + 223768         // assertionFailure(:_:file:line:flags:)
1   libswiftCore.dylib                0x00000001afb83a18 0x1afb4d000 + 223768         // assertionFailure(:_:file:line:flags:)
2   libswiftCore.dylib                0x00000001afbe6834 0x1afb4d000 + 628788         // swift_unexpectedError
3   ProtectedBrowser.dylib            0x00000001068f1f48 0x1068e8000 + 40776          // NSFileManager.__allocating_init()
4   ProtectedBrowser.dylib            0x00000001068f1fcc 0x1068e8000 + 40908          // readPrefs()
5   ProtectedBrowser.dylib            0x00000001068f2720 0x1068e8000 + 42784          // ProtectedBrowser.init()
6   ProtectedBrowser.dylib            0x00000001068f2c78 0x1068e8000 + 44152          // protocol witness for Tweak.init() in conformance ProtectedBrowser
7   Orion                             0x000000010694a208 0x106938000 + 74248          // func_120b8
8   ProtectedBrowser.dylib            0x00000001068f774c 0x1068e8000 + 63308          // orion_init()
9   ProtectedBrowser.dylib            0x00000001068f7564 0x1068e8000 + 62820          // orion_init
10  ProtectedBrowser.dylib            0x00000001068f4a94 0x1068e8000 + 51860          // init
11  dyld                              0x00000001021fa888 0x1021e0000 + 108680         // ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
12  dyld                              0x00000001021fab10 0x1021e0000 + 109328         // ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
13  dyld                              0x00000001021f4c68 0x1021e0000 + 85096          // ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
14  dyld                              0x00000001021f2bb8 0x1021e0000 + 76728          // ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
15  dyld                              0x00000001021f2c84 0x1021e0000 + 76932          // ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
16  dyld                              0x00000001021e64d0 0x1021e0000 + 25808          // dyld::runInitializers(ImageLoader*)
17  dyld                              0x00000001021ee334 0x1021e0000 + 58164          // dlopen_internal
18  libdyld.dylib                     0x00000001abb92d74 0x1abb8d000 + 23924          // dlopen_internal(char const, int, void)
19  substitute-loader.dylib           0x00000001028735e0 0x1027e0000 + 603616
20  substitute-loader.dylib           0x0000000102a32240 0x1027e0000 + 2433600
21  substitute-loader.dylib           0x0000000102a32264 0x1027e0000 + 2433636
22  substitute-loader.dylib           0x0000000102a32288 0x1027e0000 + 2433672
23  substitute-loader.dylib           0x0000000102a00aa8 0x1027e0000 + 2230952
24  substitute-loader.dylib           0x0000000102955c00 0x1027e0000 + 1530880
25  substitute-loader.dylib           0x0000000102954a48 0x1027e0000 + 1526344
26  substitute-loader.dylib           0x000000010298d2ec 0x1027e0000 + 1757932
27  substitute-loader.dylib           0x00000001029595b4 0x1027e0000 + 1545652
28  dyld                              0x00000001021fa70c 0x1021e0000 + 108300         // ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
29  dyld                              0x00000001021fab10 0x1021e0000 + 109328         // ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
30  dyld                              0x00000001021f4c68 0x1021e0000 + 85096          // ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
31  dyld                              0x00000001021f2bb8 0x1021e0000 + 76728          // ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
32  dyld                              0x00000001021f2c84 0x1021e0000 + 76932          // ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
33  dyld                              0x00000001021e64d0 0x1021e0000 + 25808          // dyld::runInitializers(ImageLoader*)
34  dyld                              0x00000001021ee334 0x1021e0000 + 58164          // dlopen_internal
35  libdyld.dylib                     0x00000001abb92d74 0x1abb8d000 + 23924          // dlopen_internal(char const, int, void)
36  substitute-inserter.dylib         0x00000001023b923c 0x1022d0000 + 954940         // func_e8f2c
37  substitute-inserter.dylib         0x00000001026f20a0 0x1022d0000 + 4333728        // func_422090
38  substitute-inserter.dylib         0x00000001026ad340 0x1022d0000 + 4051776        // func_3d1760
39  dyld                              0x00000001021fa70c 0x1021e0000 + 108300         // ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
40  dyld                              0x00000001021fab10 0x1021e0000 + 109328         // ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
41  dyld                              0x00000001021f4c68 0x1021e0000 + 85096          // ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
42  dyld                              0x00000001021f2bb8 0x1021e0000 + 76728          // ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
43  dyld                              0x00000001021f2c84 0x1021e0000 + 76932          // ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
44  dyld                              0x00000001021e27a4 0x1021e0000 + 10148          // dyld::initializeMainExecutable()
45  dyld                              0x00000001021e7d88 0x1021e0000 + 32136          // dyld::_main(macho_header const, unsigned long, int, char const, char const, char const**, unsigned long)
46  dyld                              0x00000001021e1258 0x1021e0000 + 4696           // dyldbootstrap::start(dyld3::MachOLoaded const, int, char const**, dyld3::MachOLoaded const, unsigned long*)
47  dyld                              0x00000001021e1038 0x1021e0000 + 4152           // _dyld_start

**Comment by iosrouter** [comment]
This crash is for the latest version, it occurred after I updated from v1.0.0 to current

**Comment by ginsudev** [comment]
Try the latest version, pretty sure I just fixed it

**Comment by iosrouter** [comment]
Thanks, works perfect. Also that preference screen is the best I have ever seen. Amazing job
